# Generated by Django 4.2 on 2023-04-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='img',
            field=models.ImageField(null=True, upload_to='movie_pics'),
        ),
    ]
